import {argon2,randomBytes,randomUUID,createHash,createHmac,timingSafeEqual} from 'node:crypto';
import {promisify} from 'node:util';
const derive=promisify(argon2), now=()=>Math.floor(Date.now()/1000), hash=s=>createHash('sha256').update(s).digest('hex');
export class ApiError extends Error {constructor(status,message){super(message);this.status=status;}}
const fail=(status,message)=>{throw new ApiError(status,message);};
function text(value,min,max){if(typeof value!=='string'||value.length<min||value.length>max)fail(400,'Invalid input');return value;}
function email(value){const v=text(value,3,254).trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))fail(400,'Invalid email');return v;}
function deviceInput(body){return {name:text(body.device_name,1,80).trim(),platform:['ios','android'].includes(body.platform)?body.platform:fail(400,'Invalid platform')};}
async function passwordHash(password,salt=randomBytes(16)){const key=await derive('argon2id',{message:password,nonce:salt,parallelism:1,tagLength:32,memory:65536,passes:3});return `${salt.toString('base64url')}.${key.toString('base64url')}`;}
async function matches(password,stored){const candidate=await passwordHash(password,Buffer.from(stored.split('.')[0],'base64url'));const a=Buffer.from(candidate),b=Buffer.from(stored);return a.length===b.length&&timingSafeEqual(a,b);}
export async function createAuth(store,secret){
 if(typeof secret!=='string'||Buffer.byteLength(secret)<32)throw new Error('JWT_SECRET must contain at least 32 bytes');
 const dummy=await passwordHash(randomBytes(32).toString('hex'));
 const sign=(user,device)=>{const header=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url');const payload=Buffer.from(JSON.stringify({sub:user,sid:device,iss:'bulgar-vpn',aud:'bulgar-mobile',iat:now(),exp:now()+900})).toString('base64url');const value=`${header}.${payload}`;return `${value}.${createHmac('sha256',secret).update(value).digest('base64url')}`;};
 function decode(token){try{const parts=text(token,1,4096).split('.');if(parts.length!==3)throw Error();const [h,p,s]=parts;const expected=createHmac('sha256',secret).update(`${h}.${p}`).digest();const actual=Buffer.from(s,'base64url');if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw Error();const header=JSON.parse(Buffer.from(h,'base64url'));const claim=JSON.parse(Buffer.from(p,'base64url'));if(header.alg!=='HS256'||header.typ!=='JWT'||claim.iss!=='bulgar-vpn'||claim.aud!=='bulgar-mobile'||!Number.isInteger(claim.exp)||claim.exp<=now()||typeof claim.sub!=='string'||typeof claim.sid!=='string')throw Error();return claim;}catch{fail(401,'Invalid or expired access token');}}
 async function actor(db,token){const c=decode(token);const row=await db.get('SELECT u.*, d.id AS device_id FROM users u JOIN devices d ON d.user_id=u.id WHERE u.id=? AND d.id=? AND d.revoked=0',[c.sub,c.sid]);if(!row)fail(401,'Session revoked');return row;}
 async function tokens(db,user,device){const refresh=randomBytes(32).toString('base64url');await db.run('INSERT INTO refresh_tokens(hash,user_id,device_id,expires_at) VALUES(?,?,?,?)',[hash(refresh),user,device,now()+2592000]);return {access_token:sign(user,device),refresh_token:refresh,token_type:'Bearer',expires_in:900,device_id:device};}
 async function attach(db,user,input){const count=await db.get('SELECT COUNT(*) AS n FROM devices WHERE user_id=? AND revoked=0',[user.id]);if(Number(count.n)>=user.device_limit)fail(409,'Device limit reached');const id=randomUUID();await db.run('INSERT INTO devices(id,user_id,name,platform,created_at) VALUES(?,?,?,?,?)',[id,user.id,input.name,input.platform,now()]);return tokens(db,user.id,id);}
 const tx=fn=>store.transaction(fn);
 return {
  async rateLimit(key){const bucket=createHmac('sha256',secret).update(key).digest('hex');const allowed=await tx(async db=>{const time=now();await db.run('DELETE FROM rate_limits WHERE expires_at<=?',[time]);const row=await db.get('SELECT * FROM rate_limits WHERE key=?',[bucket]);if(row&&row.hits>=20)return false;if(row)await db.run('UPDATE rate_limits SET hits=hits+1 WHERE key=?',[bucket]);else await db.run('INSERT INTO rate_limits(key,hits,expires_at) VALUES(?,?,?)',[bucket,1,time+60]);return true;});if(!allowed)fail(429,'Too many requests');},
  async register(body){const address=email(body.email),password=text(body.password,12,128),input=deviceInput(body);const encoded=await passwordHash(password);return tx(async db=>{if(await db.get('SELECT id FROM users WHERE email=?',[address]))fail(409,'Unable to register account');const user={id:randomUUID(),device_limit:5};await db.run('INSERT INTO users(id,email,password_hash) VALUES(?,?,?)',[user.id,address,encoded]);return attach(db,user,input);});},
  async login(body){const address=email(body.email),password=text(body.password,1,128),input=deviceInput(body);const user=await tx(db=>db.get('SELECT * FROM users WHERE email=?',[address]));const valid=await matches(password,user?.password_hash??dummy);if(!user||!valid)fail(401,'Invalid email or password');return tx(async db=>{const current=await db.get('SELECT * FROM users WHERE id=?',[user.id]);if(current.password_hash!==user.password_hash)fail(401,'Credentials changed');return attach(db,current,input);});},
  async refresh(body){const value=hash(text(body.refresh_token,20,200));const result=await tx(async db=>{const row=await db.get('SELECT r.*,d.revoked FROM refresh_tokens r JOIN devices d ON d.id=r.device_id WHERE r.hash=?',[value]);if(!row||row.revoked||Number(row.expires_at)<=now())return null;if(row.used){await db.run('UPDATE devices SET revoked=1 WHERE id=?',[row.device_id]);return null;}await db.run('UPDATE refresh_tokens SET used=1 WHERE hash=?',[value]);return tokens(db,row.user_id,row.device_id);});if(!result)fail(401,'Invalid refresh token');return result;},
  profile:token=>tx(async db=>{const u=await actor(db,token);return {id:u.id,email:u.email,device_limit:u.device_limit,subscription_status:u.subscription_status};}),
  devices:token=>tx(async db=>{const u=await actor(db,token);return db.all('SELECT id,name,platform,created_at FROM devices WHERE user_id=? AND revoked=0',[u.id]);}),
  revoke:(token,id)=>tx(async db=>{const u=await actor(db,token);if(!await db.get('SELECT id FROM devices WHERE id=? AND user_id=?',[id,u.id]))fail(404,'Device not found');await db.run('UPDATE devices SET revoked=1 WHERE id=?',[id]);return {ok:true};}),
  logout:(token,all=false)=>tx(async db=>{const u=await actor(db,token);await db.run(all?'UPDATE devices SET revoked=1 WHERE user_id=?':'UPDATE devices SET revoked=1 WHERE id=?',[all?u.id:u.device_id]);await db.run('UPDATE pairing_codes SET used=1 WHERE user_id=?',[u.id]);return {ok:true};}),
  async changePassword(token,body){const old=text(body.current_password,1,128),next=text(body.new_password,12,128);const u=await tx(db=>actor(db,token));if(!await matches(old,u.password_hash))fail(401,'Invalid password');const encoded=await passwordHash(next);return tx(async db=>{const current=await actor(db,token);if(current.password_hash!==u.password_hash)fail(409,'Credentials changed');await db.run('UPDATE users SET password_hash=? WHERE id=?',[encoded,u.id]);await db.run('UPDATE devices SET revoked=1 WHERE user_id=?',[u.id]);await db.run('UPDATE pairing_codes SET used=1 WHERE user_id=?',[u.id]);return {ok:true};});},
  pair:token=>tx(async db=>{const u=await actor(db,token),code=randomBytes(32).toString('base64url');await db.run('INSERT INTO pairing_codes(hash,user_id,issuer_device_id,expires_at) VALUES(?,?,?,?)',[hash(code),u.id,u.device_id,now()+90]);return {code,uri:`bulgar://pair?code=${code}`,expires_in:90};}),
  consume:body=>tx(async db=>{const input=deviceInput(body),key=hash(text(body.code,20,200));const row=await db.get('SELECT p.* FROM pairing_codes p JOIN devices d ON d.id=p.issuer_device_id WHERE p.hash=? AND p.used=0 AND d.revoked=0',[key]);if(!row||Number(row.expires_at)<=now())fail(401,'Invalid pairing code');const user=await db.get('SELECT * FROM users WHERE id=?',[row.user_id]);const result=await attach(db,user,input);await db.run('UPDATE pairing_codes SET used=1 WHERE hash=?',[key]);return result;}),
  servers:token=>tx(async db=>{await actor(db,token);return db.all('SELECT id,country,city,protocol FROM servers WHERE available=1');}),
  config:(token,id)=>tx(async db=>{const u=await actor(db,token);if(u.subscription_status!=='active')fail(403,'Active subscription required');if(!await db.get('SELECT id FROM servers WHERE id=? AND available=1',[id]))fail(404,'Server not found');fail(503,'VPN provisioning not configured');}),
  subscription:token=>tx(async db=>{const u=await actor(db,token);return {status:u.subscription_status,device_limit:u.device_limit,payment_enabled:false};})
 };
}
